[package]
name = "copilot-rs-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
quote = { version = "1", default-features = false }

[dependencies.proc-macro2]
version = "1.0.80"
default-features = false